utilitywarehouse/vault-kube-cloud-credentials

credentials.go
example/gcp-probe.yaml
go.mod
go.sum
main.go
webserver.go

By introducing additonal endpoints per-provider, we can support the extra metadata request that `gcloud` (and potentially other tooling) requires before it can request a token.

Add gcloud support

---

README.md
credentials.go
main.go

An AWS secret role in Vault can have multiple role arns associated with it. In that case you need to provide the name of the role you want to assume when you read the data from vault.

Assume a specific role

---

README.md
go.mod
main.go
operator/aws.go
operator/aws_test.go

Allow or disallow role_arns for namespaces based on a set of rules that ensure:
- The ARN is a valid ARN
- The account ID is permitted for the namespace
- The name of the role is permitted for the namespace

operator: restrict role creation based on rules

---

go.sum
main.go

We use `_` to separate elements in the names of the items the operator writes to vault. The operator needs to be able to split these items back into their constituent parts reliably in order to garbage collect items in vault and a prefix with an underscore would make this impossible.

Validate that the operator prefix does not contain an underscore

---

operator/aws.go
operator/aws_test.go

The vault client returns a nil secret when listing a backend with no keys. This was causing a panic when garbage collecting on a vault server without any existing items.
I've fixed the bug and added a test which would have caught this issue.

operator: fix panic when returned list is nil

---

go.mod
main.go
operator/aws.go
operator/aws_test.go
operator/operator.go
sidecar/credentials.go
sidecar/provider_aws.go
sidecar/provider_gcp.go
sidecar/sidecar.go
sidecar/webserver.go

By default the controller-runtime manager logs with a null logger, so in order to capture log messages internal to the manager you need to set a go-logr compatible logger.
Zap is the common one suggested by controller-runtime, so I've gone with that.
I've amended the sidecars to use it as well as the operator for the sake of consistency.
```
{"level":"info","ts":1598428325.1022131,"logger":"operator.aws","msg":"Wrote kubernetes auth backend role","namespace":"kube-system","serviceaccount":"external-dns","key":"exp-1_aws_kube-system_external-dns"}
{"level":"info","ts":1598428325.381162,"logger":"operator.aws","msg":"Wrote aws secret backend role","namespace":"kube-system","serviceaccount":"external-dns","key":"exp-1_aws_kube-system_external-dns"} …
```

add structured logging with zap

---

main.go

The config passed to the operator needs to be the same one used to instantiate the client so that the operator can reload the certificate from the environment for the config used by the client, rather than a completely irrelevant, unused, new default config.
```
2020-08-26T08:08:21.117Z    ERROR   controller      Reconciler error {"reconcilerGroup": "", "reconcilerKind": "ServiceAccount", "controller": "serviceaccount", "name": "aws-probe", "namespace": "labs", "error": "Put https://vault:8200/v1/sys/policy/exp-1_aws_labs_aws-probe: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"sys-vault CA\")"}
```

operator: use the same vault config with the client and the operator

---

go.sum
sidecar/provider_gcp.go

More GCE metadata server paths need to be mocked out for `gcloud`
and `gsutil` to work. The information that is presented by the server is
read from `gcp/roleset/<roleset name>`, so the policy attached to the
Kubernetes auth role in vault will need to allow this.

sidecar: gcp: support gcloud and gsutil

---

sidecar/sidecar.go

This logger is used by the gcp provider as well. The sidecar you are running is obvious from the command you run the sidecar with so there's no real need to indicate it in the logs.

sidecar: remove aws from logging address

---

sidecar/credentials.go

It's possible for writes to `auth/kubernetes/login` to return with a nil error AND nil auth information. This would cause a panic when trying to set the client token from a field on the nil pointer.

Return an error if the kubernetes login returns no auth information

---

README.md
go.mod
main.go
manifests/examples/aws-sidecar/aws-probe.yaml
manifests/examples/gcp-sidecar/gcp-probe.yaml
token.go
token_test.go

The sidecar is designed to work in conjunction with the operator which creates predictable names based on the namespace and service account. This name can therefore be inferred from the claims of the jwt token, which simplifies the arguments that need to be passed to the sidecar.

sidecar: infer the role names from the jwt token claims

---

go.mod
main.go
sidecar/metrics.go
sidecar/sidecar.go

- Instruments the `http.RoundTripper` used by Vault with prometheus metrics that measure the request rate and latency, as well as the number of requests currently in flight. The `vault.Config.ReadEnvironment()` function didn't play well with this because it makes a type assertion of `*http.Transport` when the underlying type has changed to `promhttp.RoundTripperFunc`. It's not a lot of work to handle this ourselves.
- Exports the expiry date of the credential lease as a metric
- Tracks the number of errors and successful renewals from the perspective of the sidecar
- Fixes the operational endpoint, which broke when we introduced gorilla/mux because, unlike http.Handle, mux.Handle only serves on one particular path.

sidecar: add prometheus metrics

---

sidecar/provider.go
sidecar/provider_aws.go
sidecar/provider_gcp.go
sidecar/sidecar.go

The sidecar was consuming tons of CPU when it couldn't retrieve credentials immediately.

sidecar: fix high CPU usage when waiting for provider to become ready

---

sidecar/provider.go
sidecar/provider_aws.go
sidecar/provider_gcp.go
sidecar/sidecar.go

The channel wasn't being created before we were writing/reading from it so it would block forever 🤦 
Fix that and move the ready channel out of the providers and into the main sidecar Run func.

sidecar: fix block introduced by non init'd channel

---

main.go
manifests/examples/aws-sidecar/aws-probe.yaml
manifests/examples/gcp-sidecar/gcp-probe.yaml

`8000` is a pretty commonly used port, `8098` should clash less.

Move default sidecar port to 8098

---

README.md
main.go
manifests/examples/operator/kustomization.yaml
manifests/examples/operator/resources/operator-config.yaml
manifests/examples/operator/vault-kube-cloud-credentials-operator-patch.yaml
manifests/operator/namespaced/vault-kube-cloud-credentials-operator.yaml
operator/aws.go
operator/aws_test.go
operator/config.go
operator/operator.go

- Pull all operator configuration from a file, rather than a combination of file and flags.
- To enable this, create a central `Operator` struct with a `New` method that reads the config file and configures the required clients.

operator: configuration from file

---

manifests/sidecar-injector/base/vault-init-container-aws-base.yaml

Allows other init container steps to use the AWS credentials provisioned by the injected container

Inject AWS init container before other init containers

---

Dockerfile

Does not clash with anything in Alpine, unlike 65533 - which is gid
"nobody" group.

Use 1000 user and group id

---

sidecar/provider_aws.go

Vault's ReadWithData can return nil error and nil object. So we need to
check that error wasn't nil, and also check if secret is not nil.

Check if returned object is nil

---

manifests/sidecar-injector/base/vault-init-container-aws-base.yaml

This will help in debugging lease duration or any other warning while creating creds

added vault debug into to aws creds file

---

manifests/sidecar-injector/base/vault-sidecar-aws-base.yaml
manifests/sidecar-injector/base/vault-sidecar-aws-gcp-base.yaml
manifests/sidecar-injector/base/vault-sidecar-gcp-base.yaml

I suspect the lack of this messes with our HPAs. From the [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#how-does-a-horizontalpodautoscaler-work):
> Please note that if some of the Pod's containers do not have the relevant resource request set, CPU utilization for the Pod will not be defined and the autoscaler will not take any action for that metric
IAM HPAs (i.e. `auth/hpa/iam-identity-api`, `auth/hpa/iam-policy-decision-api`) targeting multi-container pods are failing with: `failed to get memory utilization: missing request for memory`. HPAs of single-container pods are OK.
```
$ kubectl --context prod-aws --namespace auth get events | rg horizontal
```
Note:
* Values were roughly taken from the operator
* Probably lot less would suffice, but didn't …

Specify sidecar resource requests and limits
